if (WIN32)
    set(kitten_OS_WIN ON)
elseif (APPLE)
    set(kitten_OS_APPLE ON)

    if (IOS OR CMAKE_SYSTEM_NAME STREQUAL iOS)
        set(kitten_OS_IOS ON)
    else()
        set(kitten_OS_MACOS ON)
    endif()
else()
    set(kitten_OS_UNIX ON)

    if (ANDROID OR CMAKE_SYSTEM_NAME MATCHES "Android")
        set(kitten_OS_ANDROID ON)
    elseif(CMAKE_SYSTEM_NAME MATCHES "Linux")
        set(kitten_OS_LINUX ON)
    elseif(CMAKE_SYSTEM_NAME STREQUAL FreeBSD)
        set(kitten_OS_FREEBSD ON)
    endif()
endif()


if (kitten_OS_WIN)
    add_definitions(/DWIN32)
    add_definitions(/Dkitten_OS_WIN)
elseif(kitten_OS_APPLE)
    add_definitions(/Dkitten_OS_APPLE)

    if (kitten_OS_IOS)
        add_definitions(/Dkitten_OS_IOS)
    else()
        add_definitions(/Dkitten_OS_MACOS)
    endif()
elseif(kitten_OS_UNIX)
    add_definitions(/Dkitten_OS_UNIX)

    if (kitten_OS_ANDROID)
        add_definitions(/Dkitten_OS_ANDROID)
    elseif (kitten_OS_LINUX)
        add_definitions(/Dkitten_OS_LINUX)
    elseif (kitten_OS_FREEBSD)
        add_definitions(/Dkitten_OS_FREEBSD)
    endif()
endif()
